services:
  csgo:
    build: .
    user: "0:0"
    container_name: csgo-server
    restart: unless-stopped
    network_mode: host
    volumes:
      - /mnt/sdb4/csgo-server:/home/steam/csgo-server
      - ./cfg/server.cfg:/home/steam/csgo-server/csgo/cfg/server.cfg:ro
      - ./cfg/autoexec.cfg:/home/steam/csgo-server/csgo/cfg/autoexec.cfg:ro
    environment:
      - SRCDS_TOKEN=${GSLT_TOKEN:-}
      - SRCDS_PORT=27015
      - SRCDS_TICKRATE=128
      - SRCDS_MAXPLAYERS=12
      - SRCDS_STARTMAP=de_dust2
      - SRCDS_MAPGROUP=mg_active
      - SRCDS_GAMETYPE=0
      - SRCDS_GAMEMODE=1
      - SRCDS_FPSMAX=300
